source 'https://rubygems.org'
ruby '2.2.1'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', github: 'maccman/sinatra-contrib'
gem 'thin'
gem 'erubis'
gem 'i18n'
gem 'activesupport'
gem 'rake'
gem 'racksh'
gem 'builder'
gem 'json'
gem 'dotenv'
gem 'mail'
gem 'email_reply_parser'
gem 'dedent'
gem 'table_print'

# DB
gem 'sequel'
gem 'sinatra-sequel'
gem 'pg'
